// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTK_XFX8DYm9p0mLd5LVm4yUhkr4SYvlE',
    appId: '1:918649028332:web:7603f747083e3a8bb86fc9',
    messagingSenderId: '918649028332',
    projectId: 'personalnotes-4803f',
    authDomain: 'personalnotes-4803f.firebaseapp.com',
    storageBucket: 'personalnotes-4803f.firebasestorage.app',
    measurementId: 'G-0HYQ9PEVDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ8u84_Peem35l459mB0aStAiyumcn4sw',
    appId: '1:918649028332:android:690421d4ba3b145bb86fc9',
    messagingSenderId: '918649028332',
    projectId: 'personalnotes-4803f',
    storageBucket: 'personalnotes-4803f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqbzwOAXB5GgGFuziytEfdvkKPAplrGKs',
    appId: '1:918649028332:ios:1e141eb6bd4a4ccbb86fc9',
    messagingSenderId: '918649028332',
    projectId: 'personalnotes-4803f',
    storageBucket: 'personalnotes-4803f.firebasestorage.app',
    iosBundleId: 'com.example.personalnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqbzwOAXB5GgGFuziytEfdvkKPAplrGKs',
    appId: '1:918649028332:ios:1e141eb6bd4a4ccbb86fc9',
    messagingSenderId: '918649028332',
    projectId: 'personalnotes-4803f',
    storageBucket: 'personalnotes-4803f.firebasestorage.app',
    iosBundleId: 'com.example.personalnotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTK_XFX8DYm9p0mLd5LVm4yUhkr4SYvlE',
    appId: '1:918649028332:web:c8dd797ba62b452ab86fc9',
    messagingSenderId: '918649028332',
    projectId: 'personalnotes-4803f',
    authDomain: 'personalnotes-4803f.firebaseapp.com',
    storageBucket: 'personalnotes-4803f.firebasestorage.app',
    measurementId: 'G-59F7E6ZT9E',
  );
}
